name: Other

on:
  push:
  pull_request:

jobs:
  test:
    name: check ${{ matrix.tox_env }}
    runs-on: Ubuntu-latest
    strategy:
      matrix:
        tox_env:
        - readme

    steps:
    - uses: actions/checkout@v2
    - name: setup Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: install tox
      run: python -m pip install tox
    - name: run check for ${{ matrix.tox_env }}
      run: python -m tox -e ${{ matrix.tox_env }}
