name: Tests

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    name: ${{ matrix.os }}-Python${{ matrix.py }}
    runs-on: ${{ matrix.os }}-latest

    strategy:
      matrix:
        os:
        - Ubuntu
        - Windows
        # - MacOS
        py:
        - "3.7"
        - "3.8"
        - "3.9"
        - "3.10"
        - "3.11"

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.py }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.py }}

    # Get the latest nox
    - name: Install nox
      run: python -m pip install nox

    # Main check
    - name: Run test suite for ${{ matrix.os }}-Python${{ matrix.py }}
      run: python -m nox -s tests
